name: example
description: Example app for TIKI SDK in Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.18.0
  http: ^0.13.5
  tiki_sdk_flutter:
    path: ../.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true


  assets:
    - lib/ui/assets/images/offer_sample.png
  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: lib/ui/assets/fonts/SpaceGrotesk-Light.ttf
          weight: 300
        - asset: lib/ui/assets/fonts/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: lib/ui/assets/fonts/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: lib/ui/assets/fonts/SpaceGrotesk-SemiBold.ttf
          weight: 600
        - asset: lib/ui/assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 700
