name: tiki_sdk_flutter
description: A package for adding TIKI's decentralized infrastructure to Flutter projects. Add tokenized data ownership, consent, and rewards to your app in minutes.
version: 1.1.3
homepage: https://mytiki.com
documentation: https://docs.mytiki.com/docs
repository: https://github.com/tiki/tiki-sdk-flutter
issue_tracker: https://github.com/tiki/tiki-sdk-flutter/issues

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=3.3.4"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  path_provider: ^2.0.12
  sqlite3: ^1.9.1
  sqlite3_flutter_libs: ^0.5.12
  tiki_sdk_dart: ^1.1.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  module:
    androidX: true
    androidPackage: com.mytiki.tiki_sdk_flutter
    iosBundleIdentifier: com.mytiki.tiki-sdk-flutter

  assets:
    - lib/ui/assets/images/offer_sample.png
  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: lib/ui/assets/fonts/SpaceGrotesk-Light.ttf
          weight: 300
        - asset: lib/ui/assets/fonts/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: lib/ui/assets/fonts/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: lib/ui/assets/fonts/SpaceGrotesk-SemiBold.ttf
          weight: 600
        - asset: lib/ui/assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 700
    - family: TikiSdkIcons
      fonts:
        - asset: lib/ui/assets/fonts/TikiSdkIcons.ttf
