name: tiki_sdk_flutter
description: The Flutter implementation of TIKI's decentralized infrastructure plus abstractions to simplify the tokenization and application of data ownership, consent, and rewards. For new projects, we recommend one of our platform-specific SDKs. Same features. Much easier to implement.
version: 0.0.11
homepage: https://github.com/tiki/tiki-sdk-flutter/tiki_sdk_flutter

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  path_provider: ^2.0.11
  plugin_platform_interface: ^2.1.3
  sqlite3: ^1.9.1
  sqlite3_flutter_libs: ^0.5.12
  tiki_sdk_dart: ^0.0.11

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  module:
    androidX: true
    androidPackage: com.mytiki.tiki_sdk_flutter
    iosBundleIdentifier: com.mytiki.tikiSdkFlutter
