name: tiki_sdk_flutter
description: The TIKI SDK implementation for Flutter. Create data Ownership and Consent NFTs with TIKI.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  tiki_sdk_dart: ^0.0.5
  sqlite3: ^1.9.0
  flutter_secure_storage: ^6.0.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1