name: tiki_sdk_flutter
description: A package for adding TIKI's decentralized infrastructure to Flutter projects. Add tokenized data ownership, consent, and rewards to your app in minutes.
version: 1.1.3
homepage: https://mytiki.com
documentation: https://docs.mytiki.com/docs
repository: https://github.com/tiki/tiki-sdk-flutter
issue_tracker: https://github.com/tiki/tiki-sdk-flutter/issues

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=3.3.4"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.14
  flutter_secure_storage: ^8.0.0
  path_provider: ^2.0.13
  sqlite3: ^1.9.1
  sqlite3_flutter_libs: ^0.5.13
  tiki_sdk_dart: ^1.1.1
  permission_handler: ^10.2.0
  package_info_plus: ^3.0.3

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  module:
    androidX: true
    androidPackage: com.mytiki.tiki_sdk_flutter
    iosBundleIdentifier: com.mytiki.tiki-sdk-flutter

  fonts:
    - family: TikiSdkIcons
      fonts:
        - asset: lib/ui/assets/fonts/TikiSdkIcons.ttf

  assets:
    - lib/src/assets/data
