name: Publish iOS Frameworks

on:
  push:
    tags:
      - '*.*.*-ios'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: "Checkout TIKI SDK Flutter"
        uses: actions/checkout@v3
        with:
          repository: tiki/tiki-sdk-flutter
          path: tiki-sdk-flutter

      - name: "Setup Dart"
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.18.2

      - name: "Setup Flutter"
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.4'

      - name: "Setup XCode"
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: "Build Frameworks"
        run: |
          cd tiki-sdk-flutter
          flutter build ios-framework --output=Frameworks --no-profile --no-debug

      - name: "Zip frameworks"
        run: |
          cd tiki-sdk-flutter/Frameworks/Release
          zip -r sqlite3.xcframework.zip sqlite3.xcframework
          shasum -a 256 sqlite3.xcframework.zip | cut -f1 -d' '>> sqlite3.xcframework.checksum
          zip -r flutter_secure_storage.xcframework.zip flutter_secure_storage.xcframework
          shasum -a 256 flutter_secure_storage.xcframework.zip | cut -f1 -d' '>> flutter_secure_storage.checksum
          zip -r path_provider_ios.xcframework.zip path_provider_ios.xcframework
          shasum -a 256 path_provider_ios.xcframework.zip | cut -f1 -d' '>> path_provider_ios.checksum
          zip -r App.xcframework.zip App.xcframework
          shasum -a 256 App.xcframework.zip | cut -f1 -d' '>> App.checksum
          zip -r Flutter.xcframework.zip Flutter.xcframework
          shasum -a 256 Flutter.xcframework.zip | cut -f1 -d' '>> Flutter.checksum
          zip -r sqlite3_flutter_libs.xcframework.zip sqlite3_flutter_libs.xcframework
          shasum -a 256 sqlite3_flutter_libs.xcframework.zip | cut -f1 -d' '>> sqlite3_flutter_libs.checksum
          zip -r FlutterPluginRegistrant.xcframework.zip FlutterPluginRegistrant.xcframework
          shasum -a 256 FlutterPluginRegistrant.xcframework.zip | cut -f1 -d' '>> FlutterPluginRegistrant.checksum

      - name: Publish
        uses: ncipollo/release-action@v1
        with:
          artifacts: "tiki-sdk-flutter/Frameworks/Release/*.zip,tiki-sdk-flutter/Frameworks/Release/*.checksum"
          replacesArtifacts: false