name: Publish iOS Frameworks

on:
  push:
    tags:
      - '*.*.*-ios'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: "Checkout TIKI SDK Flutter"
        uses: actions/checkout@v3
        with:
          repository: tiki/tiki-sdk-flutter
          path: tiki-sdk-flutter

      - name: "Setup Dart"
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.18.2

      - name: "Setup Flutter"
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.4'

      - name: "Setup XCode"
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: "Build Frameworks"
        run: |
          cd tiki-sdk-flutter
          rm pubspec.yaml
          mv pubspec-frameworks.yaml pubspec.yaml
          cat pubspec.yaml
          flutter build ios-framework --output=Frameworks --no-profile

      - name: "Zip release frameworks"
        run: |
          cd tiki-sdk-flutter/Frameworks/Release
          zip -r sqlite3_release.xcframework.zip sqlite3.xcframework
          shasum -a 256 sqlite3_release.xcframework.zip | cut -f1 -d' '>> sqlite3.xcframework.checksum.txt
          zip -r flutter_secure_storage_release.xcframework.zip flutter_secure_storage.xcframework
          shasum -a 256 flutter_secure_storage_release.xcframework.zip | cut -f1 -d' '>> flutter_secure_storage.checksum.txt
          zip -r path_provider_ios_release.xcframework.zip path_provider_ios.xcframework
          shasum -a 256 path_provider_ios_release.xcframework.zip | cut -f1 -d' '>> path_provider_ios.checksum.txt
          zip -r App_release.xcframework.zip App.xcframework
          shasum -a 256 App_release.xcframework.zip | cut -f1 -d' '>> App.checksum.txt
          zip -r Flutter_release.xcframework.zip Flutter.xcframework
          shasum -a 256 Flutter_release.xcframework.zip | cut -f1 -d' '>> Flutter.checksum.txt
          zip -r sqlite3_flutter_libs_release.xcframework.zip sqlite3_flutter_libs.xcframework
          shasum -a 256 sqlite3_flutter_libs_release.xcframework.zip | cut -f1 -d' '>> sqlite3_flutter_libs.checksum.txt
          zip -r FlutterPluginRegistrant_release.xcframework.zip FlutterPluginRegistrant.xcframework
          shasum -a 256 FlutterPluginRegistrant_release.xcframework.zip | cut -f1 -d' '>> FlutterPluginRegistrant.checksum.txt
      - name: "Zip release frameworks"
        run: |
          cd tiki-sdk-flutter/Frameworks/Debug
          zip -r sqlite3_debug.xcframework.zip sqlite3.xcframework
          shasum -a 256 sqlite3_debug.xcframework.zip | cut -f1 -d' '>> sqlite3.xcframework.checksum.txt
          zip -r flutter_secure_storage_debug.xcframework.zip flutter_secure_storage.xcframework
          shasum -a 256 flutter_secure_storage_debug.xcframework.zip | cut -f1 -d' '>> flutter_secure_storage.checksum.txt
          zip -r path_provider_ios_debug.xcframework.zip path_provider_ios.xcframework
          shasum -a 256 path_provider_ios_debug.xcframework.zip | cut -f1 -d' '>> path_provider_ios.checksum.txt
          zip -r App_debug.xcframework.zip App.xcframework
          shasum -a 256 App_debug.xcframework.zip | cut -f1 -d' '>> App.checksum.txt
          zip -r Flutter_debug.xcframework.zip Flutter.xcframework
          shasum -a 256 Flutter_debug.xcframework.zip | cut -f1 -d' '>> Flutter.checksum.txt
          zip -r sqlite3_flutter_libs_debug.xcframework.zip sqlite3_flutter_libs.xcframework
          shasum -a 256 sqlite3_flutter_libs_debug.xcframework.zip | cut -f1 -d' '>> sqlite3_flutter_libs.checksum.txt
          zip -r FlutterPluginRegistrant_debug.xcframework.zip FlutterPluginRegistrant.xcframework
          shasum -a 256 FlutterPluginRegistrant_debug.xcframework.zip | cut -f1 -d' '>> FlutterPluginRegistrant.checksum.txt

    - name: Publish
        uses: ncipollo/release-action@v1
        with:
          artifacts: "tiki-sdk-flutter/Frameworks/Release/*.zip,tiki-sdk-flutter/Frameworks/Release/*.checksum.txt,tiki-sdk-flutter/Frameworks/Debug/*.zip,tiki-sdk-flutter/Frameworks/Debug/*.checksum.txt"
          replacesArtifacts: false