name: Publish Flutter

on:
  pull_request:
    branches:
      - main
    types:
      - closed

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Dart'
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.18.2

      - name: 'Setup Flutter'
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.4'

      - name: 'Setup credentials'
        run: |
          mkdir $XDG_CONFIG_HOME/dart
          echo '${{ secrets.PUB_DEV_CREDENTIALS }}' > "$XDG_CONFIG_HOME/dart/pub-credentials.json"

      - name: 'Publish SDK'
        run: |
          flutter pub publish -f

      - name: Git version
        id: version
        uses: codacy/git-version@2.4.0
        with:
          release-branch: "main"

      - name: Create a new tag
        run: |
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}

      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{steps.version.outputs.version }}
          
  docs:
    runs-on: ubuntu-latest
    needs: [ publish ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.1

      - name: Guide
        uses: readmeio/rdme@8.3.0
        with:
          rdme: docs doc/guide --key=${{ secrets.README_API_KEY }}

      - name: Ref
        uses: readmeio/rdme@8.3.0
        with:
          rdme: docs doc/ref --key=${{ secrets.README_API_KEY }}