name: Publish to Pub Dev

on:
  push:
    branches:
      - publish_to_github

jobs:
  publish_sdk:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Dart'
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.18.2

      - name: 'Setup Flutter'
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.4'

      - name: 'Setup credentials'
        run: |
          mkdir $XDG_CONFIG_HOME/dart
          echo '${{ secrets.PUB_DEV_CREDENTIALS }}' > "$XDG_CONFIG_HOME/dart/pub-credentials.json"

#      REMOVING FOR TESTING
#     - name: 'Publish SDK'
#        run: |
#          flutter pub publish -f
#

  publish_aar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Setup Dart'
          uses: dart-lang/setup-dart@v1
          with:
            sdk: 2.18.2

      - name: 'Setup Flutter'
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.4'

      - name: 'Set up Java 11'
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: 'Flutter Pub Get'
        run: |
          flutter pub get

      - name: 'Flutter Build AAR'
        run: |
          flutter build aar

      - name: 'Inject publish gradle script'
        run: |
          cat publish.gradle >> .android/build.gradle
          cd .android

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Publish package
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publish
        env:
          PUBLISH_TO_GITHUB: 1
          GITHUB_USER: 'ricardobrg'
          GITHUB_TOKEN: ${{ secrets.PACKAGES_ACCESS_TOKEN }}