name: Publish AARs

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Get Version From Tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: 'Setup Dart'
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.18.2

      - name: 'Setup Flutter'
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.4'

      - name: 'Set up Java 11'
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: 'Remove Integration Test Dependency'
        run: |
          perl -i -p0e 's/  integration_test:\n    sdk: flutter//s' pubspec.yaml

      - name: 'Flutter Pub Get'
        run: |
          flutter pub get

      - name: 'Flutter Build AAR'
        run: |
          flutter build aar

      - name: 'Append publish.gradle script'
        run: |
          cat publish.gradle >> .android/build.gradle

      - name: 'Flutter Build AAR'
        run: |
          flutter build aar --no-debug --no-profile --build-number ${{ steps.vars.outputs.tag }}
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}