name: Test

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Android:
    strategy:
      matrix:
        device:
          - "pixel_xl"
      fail-fast: false
    runs-on: macOS-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.12'

      - name: "Run offline tests"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          profile: ${{ matrix.device }}
          api-level: 29
          script: flutter test integration_test

  iOS:
    runs-on: macos-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.12'

      - name: Start iOS Simulator
        run: |
          xcrun xctrace list devices
          UDID=$(xcrun xctrace list devices | grep "^iPhone 14 Simulator (16.2) (" | awk '{gsub(/[()]/,""); print $NF}')
          echo $UDID
          xcrun simctl boot "${UDID:?No Simulator with this name found}"
      
      - name: Load TIKI Credentials    
        env:
          TIKI_CREDENTIALS: ${{ secrets.TIKI_CREDENTIALS }}
        run: |
          echo "$TIKI_CREDENTIALS" >> integration_test/tiki_credentials.dart

      - name: Run iOS Integration Tests
        run: flutter test integration_test


